fastify/fastify-autoload

- README.md
- fixtures/foo/skipAutoload.js
- index.js
- test.js
> Added skip autoload support

- README.md
- fixtures/app.js
- fixtures/foo/options.js
- index.js
- test.js
> Added custom options support

- README.md
- fixtures/app.js
- fixtures/foo/ignored.test.js
- index.js
Add ignore pattern to autoload configuration to ignore specific file in the autoload folder.
Related issue: #9
> Autoload ignore pattern

- README.md
For prevent bugs like copy paste test.
> docs: Set next() inside custom configuration

- package.json
> Greenkeeper ignore @typescript-eslint/parser

- .travis.yml
- test/error.js
> Node 12 test fix

- index.js
- test/options.js
- test/options/plugins/plugin-d.js
Fixes https://github.com/fastify/fastify-autoload/issues/61
> Fixes plugin.autoConfig on export default

- README.md
- index.js
- test/typescript/foo/shouldBeIgnored.d.ts
> Ignore TypeScript definition files

- .dependabot/config.yml
- package.json
> Use dependabot instead of greenkeeper

- index.js
This PR parallelises the loading of plugins, as per #78.
> Import plugins in parallel to reduce load times

- index.js
- test/commonjs/basic.js
- test/commonjs/basic/app.js
- test/commonjs/basic/index/bar/index.js
- test/commonjs/basic/index/index.js
I saw this [issue](https://github.com/fastify/fastify-autoload/issues/59) in fastify contribute page.. so I fixed it
- [* ] run `npm run test` and `npm run benchmark`
> fixed another directory with index file

- index.js
- test/commonjs/basic.js
- test/commonjs/basic/app.js
- test/commonjs/basic/one/index.js
- test/commonjs/basic/one/two/index.js
- test/module/basic.js
- test/module/basic/app.js
- test/module/basic/one/index.js
- test/module/basic/one/two/index.js
Hi this PR fixes the prefix aggregation issues.
Fixes #91 
Closes https://github.com/fastify/fastify/issues/2414
> Bugfix: prefix aggregation issues

- test/commonjs/cyclic-dependency/app.js
- test/commonjs/cyclic-dependency/lib/a.js
- test/commonjs/cyclic-dependency/lib/b.js
- test/commonjs/error.js
- test/commonjs/module-error/app.js
- test/commonjs/module-error/lib/a.mjs
> test: add cyclic-dependency and module-error tests

- index.js
- package.json
- test/typescript-jest/basic/app.ts
- test/typescript-jest/basic/basic.test.ts
- test/typescript-jest/basic/foo/typescript.ts
> add support to detect ts-jest environment

- .github/workflows/ci.yml
- index.js
> Fixed "error with esm on windows #98" issue

- index.js
This PR adds support for [ts-node-dev](https://github.com/whitecolor/ts-node-dev) which uses `ts-node` under the hood.
Tested and verified working on my local machine.
From the `ts-node-dev` docs:
> If you need to detect that you are running with ts-node-dev, check if process.env.TS_NODE_DEV is set.
AFAIK, no documentation changes are required as TypeScript is supported out-of-the-box by this module.
> Added support for ts-node-dev

- README.md
I was looking through the codebase and found this hidden gem, figured it would be worth documenting for other people.
> feat: document indexPattern API option

- README.md
- fastify-autoload.d.ts
- index.js
- test/module/basic.js
- test/module/basic/app.js
- test/module/basic/ten/index.js
- test/module/basic/ten/nine/index.js
> add dirNameRoutePrefix option

- fastify-autoload.d.ts
- test/typescript/definitions/fastify-autoload.test-d.ts
Add missing maxDepth property on Autoload Plugin Options Interface
> Add maxDepth on plugin options type interface

- index.js
- test/commonjs/deep.js
- test/commonjs/deep/app.js
- test/commonjs/deep/routes/level-1/level-2/routes.js
Fixed https://github.com/fastify/fastify-autoload/issues/122
> fix(#122): multiple slashes in route prefix

- README.md
- fastify-autoload.d.ts
- index.js
- test/commonjs/basic.js
- test/commonjs/basic/app.js
- test/commonjs/basic/index-pattern/custom.js
- test/commonjs/basic/index-pattern/index.js
- test/commonjs/basic/rewrite-route-prefix/index.js
- test/commonjs/basic/rewrite-route-prefix/two/index.js
- test/commonjs/basic/rewrite-route-prefix/two/three/empty/two/index.js
- test/commonjs/basic/rewrite-route-prefix/two/three/index.js
> Rewrite prefix

- .github/dependabot.yml
- .github/workflows/ci.yml
- README.md
- package.json
> ci(dependabot): auto update github actions

- fastify-autoload.d.ts
- test/typescript/definitions/fastify-autoload.test-d.ts
> Add missing types in AutoloadPluginOptions

- .github/workflows/ci.yml
- package.json
- scripts/unit.js
- test/typescript-jest/integration/integration.test.ts
It was running always on ubuntu despite the matrix config
> fix: ci should run on the matrix os

- index.js
> fix jest tests

- .taprc
- package.json
- test/commonjs/autohooks-basic.js
- test/commonjs/autohooks-cascade.js
- test/commonjs/autohooks-disabled.js
- test/commonjs/autohooks-overwrite.js
- test/commonjs/basic.js
- test/commonjs/cyclic.js
- test/commonjs/deep.js
- test/commonjs/dependency.js
- test/commonjs/options.js
- test/commonjs/route-parameters-basic.js
- test/commonjs/route-parameters-disabled.js
- test/module/autohooks.js
- test/module/basic.js
- test/module/dependency.js
- test/module/esm-import.js
- test/module/options.js
- test/module/route-parameters.js
> Support for tap v15

- index.js
- package.json
- test/commonjs/index-package.js
- test/commonjs/index-package/app.js
- test/commonjs/index-package/foo/bar.js
- test/commonjs/index-package/index.js
- test/commonjs/index-package/package.json
- test/module/index-package.js
- test/module/index-package/app.js
- test/module/index-package/foo/bar.js
- test/module/index-package/index.js
- test/module/index-package/package.json
Not really sure what `npm run benchmark` was supposed to do. There's no script for it.
Thank you! Please lemme know if I need to do anything else or if I'm misunderstanding how the package works 😂 .
> fix: allow package.json in the root of autoload dir (#188)

- index.js
- package.json
- test/commonjs/dependency/app.js
- test/commonjs/options/app.js
- test/module/dependency/app.js
- test/module/options/app.js
> fix: update error text thrown to reference new module name

- .github/workflows/ci.yml
> ci: bump shared workflow from v2 to v3

- index.js
- package.json
- test/commonjs/basic/app.js
- test/commonjs/basic/rewrite-route-prefix/two/index.js
Signed-off-by: Matteo Collina <hello@matteocollina.com>
> Update to Fastify v4

- index.js
- package.json
- scripts/unit-typescript-tsx.js
- Add [esbuild-kit/tsx](https://github.com/esbuild-kit/tsx) support. It'd be a no-brainer for fastify project using `@fastify-autoload`  and TypeScript.
One can simply use `tsx watch src/app.ts` for development or `tsx src/app.ts` in production.
> feat: add `tsx` support

- .github/workflows/ci.yml
- README.md
See https://github.com/fastify/workflows/issues/49
> ci: enable license checking

- .eslintrc.json
References a file that doesn't exist (`./tsconfig.json`) and a parser and config that aren't included as dev dependencies.
> chore: remove unused eslint config

- package.json
Used in tests but not explicitly defined as dependency:
https://github.com/fastify/fastify-autoload/blob/6a0d70bf6decb43e05300305c53ff064782d30c1/scripts/unit-typescript-esm.js#L4
> build(deps-dev): add semver

- README.md
> Fixed the wrong link.

- .github/workflows/ci.yml
- package.json
> run lint on workflow run

- index.js
- package.json
- test/commonjs/ts-node/routes/foo/index.ts
- test/commonjs/ts-node/routes/root.ts
- test/vitest/basic.test.ts
- vitest.config.ts
Alternative for #273 
@climba03003 
> forceESM for vitest

- README.md
Didn't review #327 in time before it landed. :D
> docs(readme): update typescript env variable section

- README.md
> docs(readme): fix capitalization of typescript

- index.js
See https://github.com/fastify/fastify/pull/5057
> perf(index): optimize split param

- index.js
- test/issues/374/routes/entity/.autohooks.js
- test/issues/374/routes/entity/_entity/index.js
- test/issues/374/routes/entity/index.js
- test/issues/374/routes/index.js
- test/issues/374/test.js
> fix: autohooks prefix

- index.js
> perf: extract pluginOrModulePattern

- test/commonjs/basic/encapsulate/plugin2.js
- test/issues/374/routes/entity/_entity/index.js
- test/issues/374/routes/entity/index.js
- test/issues/374/routes/index.js
- test/issues/376/routes/entity/index.js
- test/issues/376/routes/index.js
- test/issues/388/routes/foo.tsx
- test/typescript-jest/integration/instance.ts
- test/typescript-jest/integration/integration.test.ts
> test: fix jest
