fastify/fastify-autoload

README.md
fixtures/app.js
fixtures/defaultPrefix/defaultPrefix.js
fixtures/defaultPrefix/noDefaultPrefix.js
fixtures/defaultPrefix/overridePrefix.js
fixtures/defaultPrefix/prefixed.js
index.js
test.js

Using `prefix` in the default autoload options should apply a prefix for all plugins loaded by this module. This makes it so any modules then loaded by autoload appends the modules autoPrefix to the end of the default autoload prefix.
It also adds a prefixOverride to override the defaultPrefix (and autoPrefix).
I hope this is okay!

 append plugin autoPrefix to default prefix

---

README.md
index.js
test/basic.js
test/basic/foo/autoroute/get.js
test/basic/foo/autoroute/list.js
test/basic/foo/manualprefix/get.js
test/basic/foo/manualprefix/index.js
test/basic/foo/manualprefix/list.js
test/basic/foo/package/answer.js

This feature allows building routes from files automatically and prefixes the routes with the folder name.
As an example, a typical API structure:
- /services/products/list.js
- /services/products/get.js
both files have similar code:
list:
```
module.exports = function(fastify, opts, next) {
fastify.route({
method: 'GET',
url: '/',
handler: function(request, reply) {
reply.send({ hello: 'world' })
}
})
next()
}
```
get:
```
module.exports = function(fastify, opts, next) {
fastify.route({
method: 'GET',
url: '/:id',
handler: function(request, reply) {
reply.send({ hello: 'world' })
}
})
next()
}
```
Without this feature, I'd need a separate index.js file with this content:
```
module.exports = function(fastify, opts, next) {
fastify.register(require('./list')) …
```

Load multiple modules from a directory

---

README.md
index.js
test/basic.js
test/basic/foo/autowrap/get.js
test/basic/foo/autowrap/list.js

Closes #54 
The idea is to reduce the routing files to just the route schema, without wrapping everything into a fastify plugin in every file. It's a cosmetic change.
I'm missing the docs part. Let me know if everything is good to go, then I'll add the part to the README.

Automatically wrap full routes into fastify plugins

---

README.md
index.js
package.json
test/options.js
test/options/app.js
test/options/lib-plugin.js
test/options/plugins-2/plugin-x.js
test/options/plugins-3/plugin-y.js
test/options/plugins/plugin-a.js
test/options/plugins/plugin-b.js
test/options/plugins/plugin-c.js

This allows plugins to declare their own default options, keys are overridden by custom options provided to autoload. Using the `options` namespace corresponds with `fastify-cli` `-o` flag functionality for the entry point plugin.
Beyond the declarative and convenience benefits this also supports a novel pattern where ecosystem plugins are configured in their own files - which for large scale applications may be easier to manage than in a single entry point. 
For instance consider the following: 
```js
const helmet = require('fastify-helmet')
helmet.options = { referrerPolicy: true }
module.exports = helmet
```

support plugin.autoConfig

---

README.md
index.js
test/commonjs/basic.js
test/commonjs/basic/index/ignored.js

--------------------------------------------
This PR assume that the desired behaviour for a directory containing an `index.js` file is to not load the files next to the `index.js` but load the modules in the potential sub-directories next to `index.js`:
```
routes
├── index.js // loaded
├── routeA.js // ignored
└── sub
└── routeB.js // loaded
```

Doesn't load the modules next to an index.js file (fix #90)

---

README.md
index.js
test/module/basic.js
test/module/basic/app.js
test/module/basic/nested/shallow/deep/deeper/index.js
test/module/basic/nested/shallow/deep/index.js
test/module/basic/nested/shallow/index.js

Relates to #89. However, instead of toggling recursion this provides the ability to set the maximum depth of nesting that plugins will be loaded at. 
Setting `maxDepth: 1` would be the equivalent of `recursive: false`, and setting `maxDepth: 0` would allow for a flattened directory structure like so:
```
plugins/
|__  pluginOne.js
|__  pluginTwo.js
|__  lib/
|__  utilOne.js
|__  utilTwo.js
```
Confirm the added unit tests pass.

Add maxDepth option.

---

package.json
test/typescript-jest/integration/instance.ts
test/typescript-jest/integration/integration.test.ts

Resolve #102 
I do not know if it is the right approach for testing ```ts-node``` and ```ts-node-dev``` integration. But I think it is the only way to see if it is working properly.
The two test case increase the test time from 1S to 8S and I think it is not worth for such two test case.

test: add test for env integration

---

fastify-autoload.d.ts
index.js
test/module/esm-import.js
test/module/esm-import/app.js
test/module/esm-import/plugins/default/index.js
test/module/esm-import/plugins/named/index.js
test/module/esm-import/plugins/star-default/index.js
test/module/esm-import/plugins/star-named/index.js
test/typescript/basic/app.ts
test/typescript/definitions/fastify-autoload.test-d.ts

When importing autoload using `import autoload from 'fastify-autoload'` I get an error which `Error: plugin must be a function or a promise`.
Using commonjs syntax works fine but I believe we want to make it work in both scenarios.
I changed the unit test which was using `require` to include autoload.
PS
I also believe this might be the fix needed [here](https://github.com/fastify/fastify-cli/issues/303) too.

fix: fixed error when importing using esm syntax

---

README.md
index.js
test/commonjs/basic.js
test/commonjs/basic/app.js
test/commonjs/basic/foo/decorator.js

This PR address a severe regression in v3.5.0: decorated values will not be accessible outside of the autoload context, breaking our default template in fastify-cli.

Fix decorator support when not using autoHooks.

---

README.md
fastify-autoload.d.ts
index.js
package.json
scripts/unit-typescript-esm.js
scripts/unit.js
test/typescript-esm/app/index.ts
test/typescript-esm/forceESM.ts
test/typescript-esm/package.json
test/typescript/definitions/fastify-autoload.test-d.ts

This PR adds the `forceESM` option, which always uses `await import` to load modules despite of the detected package type.
I run into this when running code via `ts-node` in a folder where `package.json` had `type='module'`.
I also tried to add a test for this, but I was not able to reproduce the problem in this repo, since `type!='module'`.

feat: Added forceESM option.

---

README.md
index.js
test/commonjs/route-parameters-basic.js
test/commonjs/route-parameters-disabled.js
test/commonjs/route-parameters/basic.js
test/commonjs/route-parameters/disabled.js
test/commonjs/route-parameters/routes/users/_id/actions.js
test/commonjs/route-parameters/routes/users/index.js
test/module/route-parameters.js
test/module/route-parameters/basic.mjs
test/module/route-parameters/disabled.mjs
test/module/route-parameters/routes/index.mjs
test/module/route-parameters/routes/pages/_id/actions.mjs
test/module/route-parameters/routes/pages/routes.mjs
test/module/route-parameters/routes/users/_id/actions.mjs

Adds route parameters based on underscore-prefixed folders. See #133 

feat: route parameters

---

fastify-autoload.d.ts
test/typescript/definitions/fastify-autoload.test-d.ts

fix: add missing type routeParams

---

README.md

Removed unnecessary import path from 'path', inside example.

docs: removed unnecessary import

---

package.json
test/typescript-esm/app/index.ts
test/typescript/basic.ts

Closes #173 
This PR bumps `tsd` to version `0.17` weirdly enough the update did not cause anything to break and instead the bot's PR failed because of a problem on npm as detailed on the CI error logs, `ts-node` has been updated to version `10.1.0` and a `@types/tap` was installed as a new devDependency, this was required as typescript refused to compile without tap's type definition files.

Bump `ts-node` & `tsd`

---

.swcrc
index.js
package.json
scripts/unit-typescript-swc.js

- Add `@swc/core` transpiler support so that the consumer project can run typescript via `@swc/register` require hook.
- Related to #190.
Please let me know if the PR is okay, not sure the benchmark things though.
---

Add SWC support

---

index.js
package.json
scripts/unit-typescript-tsm.js

- Add [tsm](https://github.com/lukeed/tsm) loader support so that people can run typescript via `tsm` require hook.
- Add a test code that runs in a non-TS node environment.
- Please let me know if the PR is okay.
I'm sorry, but I'm not sure about the benchmark, I could not found the `npm run benchmark`
---

Add tsm support

---

.github/workflows/ci.yml
package.json

Testing the new reusable workflow

chore: testing new reusable workflow

---

fastify-autoload.d.ts
package.json
test/typescript-esm/forceESM.ts
test/typescript-jest/basic/app.ts
test/typescript-jest/basic/foo/typescript.ts
test/typescript-jest/integration/integration.test.ts
test/typescript/basic.ts
test/typescript/basic/app.ts
test/typescript/basic/foo/typescript.ts
test/typescript/definitions/fastify-autoload.test-d.ts

Hello.
This PR aims to :
- fix some flacky tests that randomly failed on CI runs
- update some deprecated tap `deepEqual` tests to the recommended `same` function
- update typescript definitions and tests
- upgrade package dependencies

fix (test): fixed some flacky tests and updated typescript definitions

---

README.md
fastify-autoload.d.ts
index.js
package.json
test/commonjs/basic.js
test/commonjs/basic/app.js
test/commonjs/basic/encapsulate/plugin1.js
test/commonjs/basic/encapsulate/plugin2.js
test/typescript/definitions/fastify-autoload.test-d.ts

Adding the option below:
`encapsulate` (optional) - Defaults to `true`, if set to `false` each plugin loaded is wrapped with [fastify-plugin](https://github.com/fastify/fastify-plugin). This allows you to share contexts between plugins and the parent context if needed. For example, if you need to share decorators. Read [this](https://github.com/fastify/fastify/blob/main/docs/Reference/Encapsulation.md#sharing-between-contexts) for more details.
```js
fastify.register(autoLoad, {
dir: path.join(__dirname, 'plugins'),
encapsulate: false
})
```

feat: adding `encapsulate` option with default `true`, non-breaking change

---

README.md
index.js
test/commonjs/route-parameters-basic.js
test/commonjs/route-parameters/routes/__country-__language/actions.js

This fixes #197 and allows multiple route params to be configure in the path name. 
I've opted to use an additional route prefix (`__`) since folders and routes could contain a regular `_` in the name and that could break auto loading in unexpected ways.

adds mixed route params

---

index.js
package.json
scripts/unit-typescript-swc-node-register.js

This adds support for [@swc-node/register](https://github.com/swc-project/swc-node), a ts-node alternative from the SWC project.
*I ran the tests, but there is no benchmark script.*
Note that although I added a TypeScript unit test file for this change, I could not get the test to *fail*, even before adding my changes to `typescriptSupport`.
An additional question: Would you be open to adding a `FASTIFY_AUTOLOAD_TS` environment variable that can be used to force TypeScript support? Otherwise, I feel people are going to hack things like setting `JEST_WORKER_ID` when they have TypeScript support, but this package isn't aware of it.

Add support for @swc-node/register

---

index.js
package.json
test/commonjs/error.js
test/commonjs/ts-node.js
test/commonjs/ts-node/routes/foo/index.ts
test/commonjs/ts-node/routes/root.ts
test/vitest/basic.test.ts
vitest.config.ts

This branch adds support for `.ts` files when the application is not run with `ts-node.` The specific use case for this is mentioned in #230. Vitest does not run with `ts-node` (it uses `es-build`) to compile TypeScript. This creates a situation where some`.ts` files that AutoLoad tries to import fails because there is no Typescript transpiler.
This pull request resolves #230.
Replace lines 32-42 in `test/commonjs/error.js` with `app3.register(require('./index-error/app'))`. This will cause the plugin to load `ts-node` from the Node modules and not throw an error to the user that they need to install `ts-node`.
Replace `index.js` with the current version of the file in the `master` branch. This will cause the test files in `test/commonjs/ts-node.js` to error because it cannot load `.ts` …

Add support for .ts files when app is not run with ts-node.

---

index.js
test/commonjs/non-plugin.js
test/commonjs/non-plugin/app.js
test/commonjs/non-plugin/lib/a-plugin.js
test/commonjs/non-plugin/lib/non-plugin.js

If this plugin encounters an export like:
```js
module.exports = {
foo: 'foo'
}
```
It will attempt to load it like any other Fastify plugin. This results in `avvio` complaining that it received an object when it was expecting a function. Such an error is _very_ difficult to track down because the offending source file reference is long lost by the time `avvio` is involved. In order to prevent this, this pull request adds code to validate the required data as being either a legitimate Fastify plugin, or an object that can be reasonably assumed to be capable of becoming one (i.e. wrapped into a plugin automatically). Otherwise, it will silently ignore that file.

Skip loading of non-plugin-like entities

---

index.js
test/commonjs/babel-node.js
test/commonjs/babel-node/routes/foo/index.ts
test/commonjs/babel-node/routes/root.ts
test/typescript-jest/babel-node/index.test.ts

- when dealing with typescript files, we need to make sure the ts-node is being used to autoload components
- closes: https://github.com/fastify/fastify-autoload/issues/271

271: trying to use babel-node when using typescript files

---

index.js
package.json
scripts/unit-typescript-esbuild.js

What I did
Add [esbuild-register](https://github.com/egoist/esbuild-register) support. One of the many libraries to execute typescript files on the fly

add esbuild-register support

---

package.json
scripts/unit-typescript-esbuild.js
scripts/unit-typescript-esm.js
scripts/unit-typescript-swc-node-register.js
scripts/unit-typescript-swc.js
scripts/unit-typescript-tsm.js
scripts/unit-typescript-tsx.js
scripts/unit.js
test/commonjs/error.js

We support node >= 14, so we dont need semver anymore.

remove semver

---

README.md
index.js
package.json
test/commonjs/ts-node/routes/bar/index.ts
test/commonjs/ts-node/routes/foo/baz/index.ts
test/vitest/filter.test.ts
types/index.d.ts
types/index.test-d.ts

Fix #287 
So, I added the `matchFilter` and `ignoreFilter` optional options that can accepts
- string
- RegExp
- function returning a boolean
I ended up letting `ignorePattern` as is for compatibility.
`ignorePattern` only check the file name, whereas `matchFilter` and `ignoreFilter` check the whole path (prefix + file name)
I added some tests and a documentation.

Add matchFilter and ignoreFilter

---

test/vitest/filter.test.ts
types/index.d.ts
types/index.test-d.ts

I'm so sorry, I messed up the typescript type as I changed filter functions prototype when developing this feature https://github.com/fastify/fastify-autoload/issues/287 😥 ...
Basically, at one point of dev, filter functions had a prototype of `({path:string, file:string})=>boolean`, but I changed it for `(path:string)=>boolean` since I found it more convenient. I used the correct prototype in the documentation, though.
I updated a test to use a filter functions.

Fix: Incorrect Filter type

---

index.js
test/commonjs/ts-node/routes/bar/index.ts
test/commonjs/ts-node/routes/foo/baz/index.ts
test/commonjs/ts-node/routes/foo/index.ts
test/vitest/basic.test.ts
test/vitest/filter.test.ts

Fix https://github.com/fastify/fastify-autoload/issues/291
I'm so sorry, the matchFilter and ignoreFilter didn't have the correct behavior when `dirNameRoutePrefix` was altered...
So I used the real file path relative to the root dir.
⚠️ There were a problem with windows with the backslashes. I considered using [unjs/pathe](https://www.npmjs.com/package/pathe), but I felt like this was not necessary to add a package for such a tiny usecase. So I simply used a `replaceAll`, tell me if that's okay.
I also update the test routes responses to `{[name of route]: "[name of the route]"}` for better readability.
I can revert that if you prefer the old way.

Fix file path for filters

---

README.md
index.js
types/index.test-d.ts

- Changed capture groups `(...)` to non-capture groups `(?:...)`, as nothing is done with the captured text in this plugin
- Added `^` to beginning of patterns in the documentation examples starting with `.*`, as ReDoS checkers flag these as vulnerable
- Slapped a closing `$` on the one example in the documentation without it

refactor(index): convert unused capture groups to non-capture groups 

---

index.js
scripts/unit-typescript-esbuild.js
scripts/unit-typescript-esm.js
scripts/unit-typescript-swc-node-register.js
scripts/unit-typescript-swc.js
scripts/unit-typescript-tsm.js
scripts/unit-typescript-tsx.js
scripts/unit.js
test/commonjs/autohooks/basic.js
test/commonjs/autohooks/cascade.js
test/commonjs/autohooks/disabled.js
test/commonjs/autohooks/overwrite.js
test/commonjs/babel-node.js
test/commonjs/basic/app.js
test/commonjs/cyclic-dependency/app.js
test/commonjs/deep/app.js
test/commonjs/dependency/app.js
test/commonjs/graph-dependency/app.js
test/commonjs/index-error/app.js
test/commonjs/module-error/app.js
test/commonjs/non-plugin/app.js
test/commonjs/options/app.js
test/commonjs/route-parameters/basic.js
test/commonjs/route-parameters/disabled.js
test/commonjs/syntax-error/app.js
test/commonjs/ts-error/app.js

See https://github.com/fastify/fastify-static/pull/407

perf: use `node:` prefix to bypass require.cache call for builtins

---

README.md
index.js

implement a reasonable workaround for #309 

feat: add FASTIFY_AUTOLOAD_TYPESCRIPT environment variable

---

index.js

- Changed capture group `(...)` to non-capture group `(?:...)`, as nothing is done with the captured text in this plugin, the regex engine is doing extra work capturing text only to end up not using it
- Added the `u` unicode flag to every regex pattern, which [acts as a strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode#description) for regex
- Removed a redundant `i` case-insensitive flag from a pattern that had no word characters in it

perf(index): convert unused capture group to non-capture group

---

test/commonjs/autohooks/routes/child/grandchild/routes.js
test/commonjs/autohooks/routes/child/routes.js
test/commonjs/autohooks/routes/routes.js
test/commonjs/autohooks/routes/sibling/routes.js
test/commonjs/basic/encapsulate/plugin1.js
test/commonjs/basic/encapsulate/plugin2.js
test/commonjs/basic/foo/autowrap/get.js
test/commonjs/basic/foo/autowrap/list.js
test/commonjs/basic/foo/manualprefix/index.js
test/commonjs/basic/index-pattern/custom.js
test/commonjs/basic/index-pattern/index.js
test/commonjs/basic/index/bar/index.js
test/commonjs/basic/index/ignored.js
test/commonjs/basic/index/index.js
test/commonjs/basic/one/index.js
test/commonjs/basic/one/two/index.js
test/commonjs/basic/rewrite-route-prefix/index.js
test/commonjs/basic/rewrite-route-prefix/two/index.js
test/commonjs/basic/rewrite-route-prefix/two/three/empty/two/index.js
test/commonjs/basic/rewrite-route-prefix/two/three/index.js
test/commonjs/basic/routeParams/foo/_id1/bar/_id2/index.js
test/commonjs/basic/routeParams/foo/_id1/index.js
test/commonjs/basic/routeParams/foo/index.js
test/commonjs/basic/routeParams/index.js
test/commonjs/route-parameters/routes/__country-__language/actions.js
test/commonjs/route-parameters/routes/users/_id/actions.js
test/commonjs/route-parameters/routes/users/index.js

test(commonjs): add missing `use strict` directives

---

index.js
package.json

The `getPackageType` function needlessly relied on the `pkg-up` package tree. While unnecessary, it also caused `@fastify/autoload` to not work with Bun.
Have run `lint:fix` and `test` with no issues. All changes are internal and require no documentation changes.
Not sure the other requirements for contributing to Fastify.

chore: remove `getPackageType` deps, fix for Bun

---

index.js
test/issues/326/test.js
test/issues/376/routes/entity/.autohooks.js
test/issues/376/routes/entity/index.js
test/issues/376/routes/index.js
test/issues/376/test.js

Since no core member add value to https://github.com/fastify/fastify-autoload/issues/376#issuecomment-2129429693
I want to move things forward to users desire behavior.
Fixes #376 
As mention in last submitted PR, I believe the long term solution is refactor the code to create a single tree that contain both `hook` and `plugin` information.

fix: autohooks prefix concatenation

---

README.md
index.js
test/commonjs/basic.js
test/commonjs/basic/foo/configPrefix.js
test/commonjs/basic/foo/configPrefixCallback.js
test/commonjs/options.js
test/commonjs/options/plugins/plugin-e.js
test/module/basic.js
test/module/basic/foo/configPrefix.js
test/module/basic/foo/configPrefixCallback.js
test/module/options.js
test/module/options/plugins/plugin-e.js

Can be usefull to autoload plugins:
```js
import fastifyMysql from "@fastify/mysql";
export const autoConfig = (fastify) => {
return {
promise: true,
host: fastify.config.MYSQL_HOST,
user: fastify.config.MYSQL_USER,
password: fastify.config.MYSQL_PASSWORD,
database: fastify.config.MYSQL_DATABASE,
port: Number(fastify.config.MYSQL_PORT)
}
}
export default fastifyMysql
```

Allow `autoConfig` with callback

---

README.md
test/issues/388/routes/foo.tsx
test/issues/388/test.js

docs: document possibility to parameter scriptPattern
